import { Metadata } from "next";
import dynamic from "next/dynamic";

const FavouritePage = dynamic(
  () => import("@/app/ui/favourite/FavouritePage"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Halaman produk favorit",
  description: "Generated by create next app",
};

export default function Page() {
  return <FavouritePage />;
}
