import AccountPage from "@/app/ui/account/account-page";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Akun saya",
  description: "Generated by create next app",
};

export default function Page() {
  return <AccountPage />;
}
