import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { poppins } from "@/app/ui/fonts";
import GlobalProvider from "@/app/providers/global-provider";
import { StoreProvider } from "@/app/providers/store-provider";
import { authOptions } from "./api/auth/[...nextauth]/auth-options";
import Footer from "@/app/ui/footer";
import Navbar from "@/app/ui/navbar/navbar";

export const metadata: Metadata = {
  title: {
    template: "Olshop | %s",
    default: "Olshop",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StoreProvider>
          <GlobalProvider session={session}>
            <main>
              <div className={`flex flex-col justify-between h-screen`}>
                <Navbar />
                <div className="flex-1 mt-32 mb-24 mx-5 md:container md:mx-auto">
                  {children}
                </div>
                <Footer />
              </div>
            </main>
          </GlobalProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
