import { Metadata } from "next";
import dynamic from "next/dynamic";
import { cookies } from "next/headers";

const PaymentPage = dynamic(() => import("@/app/ui/payment/payment"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Pembayaran",
  description: "Generated by create next app",
};

export default function Page() {
  const tsToken = cookies().get("ts-token")?.value;
  return <PaymentPage tsToken={tsToken} />;
}
