import { Metadata } from "next";
import dynamic from "next/dynamic";

const CartPage = dynamic(() => import("@/components/pages/CartPage"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Halaman keranjang",
  description: "Generated by create next app",
};

export default async function Page() {
  return <CartPage />;
}
