import ImageLoad from "@/app/ui/image-load";
import AuthForm from "@/app/ui/auth-form";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function SignUp() {
  return (
    <div className="grid grid-cols-2 justify-between items-center">
      <div>
        <div className="mb-5">
          <h3 className="text-lime-950 font-bold text-5xl">
            Buat akun anda secara gratis!
          </h3>
          <p className="text-sm font-semibold text-gray-400 mt-2">
            Lengkapi kredensial akun anda untuk melanjutkan
          </p>
        </div>
        <AuthForm isSignUp />
      </div>

      <div>
        <ImageLoad
          className="h-96 w-full"
          src="/images/sign-up-img.png"
          alt="sign-up-img"
        />
      </div>
    </div>
  );
}
