import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Halaman produk favorit",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <p>Favourite</p>
    </div>
  );
}
