import Footer from "@/components/guest/Footer";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Suspense } from "react";
import "../globals.css";
import Loading from "./home/loading";

const Navbar = dynamic(() => import("@/components/guest/Navbar"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: {
    template: "Olshop | %s",
    default: "Olshop",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`flex flex-col justify-between h-screen`}>
      <Navbar />
      <Suspense fallback={<Loading />}>
        <div className="flex-1 mt-32 mb-24 container">{children}</div>
      </Suspense>
      <Footer />
    </div>
  );
}
