import { AllProduct } from "@/app/ui/product/all-product";
import { ProductSkeleton } from "@/app/ui/product/product-skeleton";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Produk",
  description: "Generated by create next app",
};

export default function Page({
  searchParams,
}: {
  searchParams: {
    query: string;
  };
}) {
  const query = searchParams?.query || "";
  return (
    <div>
      <Suspense fallback={<ProductSkeleton />}>
        <AllProduct query={query} />
      </Suspense>
    </div>
  );
}
