import { AllProduct } from "@/app/ui/product/all-product";
import { ProductSkeleton } from "@/app/ui/product/product-skeleton";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Produk",
  description: "Generated by create next app",
};

export default function Page({
  searchParams,
}: {
  searchParams?: {
    page?: string;
    query?: string;
  };
}) {
  const page = searchParams?.page || "1";
  const query = searchParams?.query || "";

  return (
    <div>
      {query && (
        <h3 className="font-semibold text-3xl my-4">
          Hasil pencarian {`\'${query}\'`}
        </h3>
      )}
      <Suspense fallback={<ProductSkeleton />}>
        <AllProduct query={query} page={page} />
      </Suspense>
    </div>
  );
}
