import ProductDetail from "@/app/ui/product/ProductDetailPage";
import { getProductById } from "@/get-data/getProducts";
import { Suspense } from "react";
import Loading from "./loading";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Detail produk",
  description: "Generated by create next app",
};

export default async function Page({
  params,
  searchParams,
}: {
  params: { productId: string };
  searchParams?: { [key: string]: string | string[] | undefined };
}) {
  const productId = params.productId;
  const product = await getProductById(productId);

  return (
    <Suspense fallback={<Loading />}>
      <ProductDetail product={product.data} />
    </Suspense>
  );
}
