import { fetchProductById } from "@/app/lib/data";
import { ProductDetail } from "@/app/ui/product/product-detail";
import ProductDetailSkeleton from "@/app/ui/skeletons/ProductDetailSkeleton";

import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Detail produk",
  description: "Generated by create next app",
};

export default async function Page({
  params,
  searchParams,
}: {
  params: { productId: string };
  searchParams?: { [key: string]: string | string[] | undefined };
}) {
  const product = await fetchProductById(params.productId);
  return (
    <Suspense fallback={<ProductDetailSkeleton />}>
      <ProductDetail product={product} />
    </Suspense>
  );
}
