import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pesanan saya",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <p>My order page</p>
    </div>
  );
}
