import { getCategories } from "@/get-data/getCategories";
import { getProducts } from "@/get-data/getProducts";
import { Metadata } from "next";
import dynamic from "next/dynamic";

const Homepage = dynamic(() => import("@/components/pages/HomePage"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Halaman Utama",
  description: "Generated by create next app",
};

export default async function Page() {
  const products = await getProducts();
  const categories = await getCategories();
  return <Homepage products={products} categories={categories} />;
}
