import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pembayaran sukses",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <p>Pembayaran berhasil</p>
    </div>
  );
}
