import PaymentPage from "@/components/pages/PaymentPage";
import { cookies } from "next/headers";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Halaman pembayaran",
  description: "Generated by create next app",
};

export default function Page() {
  const cookie = cookies();
  const tsToken = cookie.get("ts-token")?.value;
  return <PaymentPage tsToken={tsToken} />;
}
