import { fetchCategories } from "@/app/lib/data";
import { Banner } from "@/app/ui/banner";
import MobileCategory from "@/app/ui/category/mobile-category";
import { SideCategory } from "@/app/ui/category/side-categories";
import { SideCategorySkeleton } from "@/app/ui/category/skeleton";
import { AllProduct } from "@/app/ui/product/all-product";
import { ProductSkeleton } from "@/app/ui/product/product-skeleton";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Suspense } from "react";
import { authOptions } from "@/app/(route)/api/auth/[...nextauth]/auth-options";

export const metadata: Metadata = {
  title: "Halaman Utama",
  description: "Generated by create next app",
};

export default async function Page({
  searchParams,
}: {
  searchParams?: {
    category?: string;
    page?: string;
  };
}) {
  const category = searchParams?.category || "";
  const page = searchParams?.page || "1";
  const categories = await fetchCategories();
  const session = await getServerSession(authOptions);

  return (
    <div className="flex flex-col gap-2">
      <Banner />
      <div className="flex flex-col md:flex-row mt-5 gap-2">
        <div className="hidden md:block">
          <Suspense fallback={<SideCategorySkeleton />}>
            <SideCategory categories={categories} />
          </Suspense>
        </div>
        <div className="block md:hidden">
          <MobileCategory categories={categories} />
        </div>
        <div className="flex-grow">
          <Suspense fallback={<ProductSkeleton />}>
            <AllProduct category={category} session={session} page={page} />
          </Suspense>
        </div>
      </div>
    </div>
  );
}
