import { fetchCategories } from "@/app/lib/data";
import { Banner } from "@/app/ui/banner";
import { SideCategory } from "@/app/ui/category/side-categories";
import { SideCategorySkeleton } from "@/app/ui/category/skeleton";
import { AllProduct } from "@/app/ui/product/all-product";
import { ProductSkeleton } from "@/app/ui/product/product-skeleton";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Halaman Utama",
  description: "Generated by create next app",
};

export default async function Page({
  searchParams,
}: {
  searchParams?: {
    category?: string;
  };
}) {
  const category = searchParams?.category || "";
  const categories = await fetchCategories();
  return (
    <div className="flex flex-col gap-2">
      <Banner />
      <div className="flex mt-5 gap-2">
        <div>
          <Suspense fallback={<SideCategorySkeleton />}>
            <SideCategory categories={categories} />
          </Suspense>
        </div>
        <div className="flex-grow">
          <Suspense fallback={<ProductSkeleton />}>
            <AllProduct category={category} />
          </Suspense>
        </div>
      </div>
    </div>
  );
}
