import CartMobile from "@/app/ui/cart/cart-mobile";
import { CartSkeleton } from "@/app/ui/cart/skeleton";
import { Metadata } from "next";
import dynamic from "next/dynamic";
import { Suspense } from "react";

const CartTable = dynamic(() => import("@/app/ui/cart/table"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Halaman keranjang",
  description: "Generated by create next app",
};

export default async function Page() {
  return (
    <Suspense fallback={<CartSkeleton />}>
      <div>
        <h3 className="text-2xl md:text-3xl mb-5 font-semibold  text-center">
          Halaman Keranjang
        </h3>
        <div className="hidden md:block">
          <CartTable />
        </div>
        <div className="block md:hidden mt-5">
          <CartMobile />
        </div>
      </div>
    </Suspense>
  );
}
